model:
  module: my_model
  class_name: MyModel

preprocessing:
  module: my_preprocessing
  class_name: MyPreprocessing

database:
  provider: postgresql
  database: users
  user: postgres
  password: admin
  host: localhost
  port: 5432
  table_info:
    table_name: embeddings
    cube_dim: 64

redis:
  host: localhost
  port: 6379
  db: 0

use_jwt: False
