model:
  module: my_model
  class_name: Model

preprocessing:
  module: my_preprocessing
  class_name: Preprocessing

database:
  provider: mysql
  database: embeddings
  user: root
  password: admin
  host: localhost
  port: 3306
  table_info:
    table_name: embeddings

redis:
  host: localhost
  port: 6379
  db: 0
